apiVersion: apps/v1
kind: Deployment
metadata:
  name: people
spec:
  selector:
    matchLabels:
      app: people
  template:
    metadata:
      labels:
        app: people
    spec:
      containers:
      - name: people
        image: practice/people
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080