---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      args: ["--context=git://github.com/jeromecsv/practice",
             "--destination=froztfire/people:1.0.0"]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred1
        items:
          - key: .dockerconfigjson
            path: config.json